name: Bina AZ Bot

on:
  workflow_dispatch: # Biz düyməni basanda işləsin

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Kodu götür
        uses: actions/checkout@v3

      - name: Python quraşdır
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Kitabxanaları yüklə
        run: pip install requests beautifulsoup4

      - name: Botu işlət
        run: python main.py
