name: Bina AZ Bot

on:
  schedule:
    - cron: '*/5 * * * *' # Bu botu hər 5 dəqiqədən bir öz-özünə işlədir
  workflow_dispatch: # Düymə də qalsın ki, istəyəndə özün də basasan

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Kodu götür
        uses: actions/checkout@v3

      - name: Python quraşdır
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Kitabxanaları yüklə
        run: pip install requests beautifulsoup4

      - name: Botu işlət
        run: python main
